// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqb2cCEOgSnzCcUq9_9yQizg8GarZzB0o',
    appId: '1:868807121941:web:86e501645062cda2e1821c',
    messagingSenderId: '868807121941',
    projectId: 'minimalshopauth',
    authDomain: 'minimalshopauth.firebaseapp.com',
    storageBucket: 'minimalshopauth.firebasestorage.app',
    measurementId: 'G-DEKR7FQTDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtoPSCqlXAR9I_mlK4-TbRKARZqcx-8j8',
    appId: '1:868807121941:android:284d560e2a4cd46be1821c',
    messagingSenderId: '868807121941',
    projectId: 'minimalshopauth',
    storageBucket: 'minimalshopauth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXNR-i1pkQgjVtcX4stIkbvDue8Q1YMzs',
    appId: '1:868807121941:ios:efb8a6ced11db993e1821c',
    messagingSenderId: '868807121941',
    projectId: 'minimalshopauth',
    storageBucket: 'minimalshopauth.firebasestorage.app',
    iosBundleId: 'com.example.minimalShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXNR-i1pkQgjVtcX4stIkbvDue8Q1YMzs',
    appId: '1:868807121941:ios:efb8a6ced11db993e1821c',
    messagingSenderId: '868807121941',
    projectId: 'minimalshopauth',
    storageBucket: 'minimalshopauth.firebasestorage.app',
    iosBundleId: 'com.example.minimalShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqb2cCEOgSnzCcUq9_9yQizg8GarZzB0o',
    appId: '1:868807121941:web:76de5f9665cd472ee1821c',
    messagingSenderId: '868807121941',
    projectId: 'minimalshopauth',
    authDomain: 'minimalshopauth.firebaseapp.com',
    storageBucket: 'minimalshopauth.firebasestorage.app',
    measurementId: 'G-X45JZGYEEY',
  );

}